version: "3.8"
services:
### MYSQL Database ###
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: Decagon@2022
      MYSQL_DATABASE: fullstack
      MYSQL_TCP_PORT: 3307
    restart: always
#    volumes:
#      - mysql_db_data:/var/lib/mysql

### MySQL Adminer ###
  adminer:
    container_name: adminer_container
    image: adminer
    depends_on:
      - mysql
    environment:
        ADMINER_DEFAULT_SERVER: mysql
        ADMINER_DESIGN: galkaev
    ports:
      - "8888:8888"
    restart: always

  ### API Spring Boot ###

  server:
    container_name: appserver
    image: omenka/fullstack_build
    depends_on:
      - mysql
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/fullstack?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    ports:
          - "8080:8080"
    restart: always