version: "3.8"
services:
### MYSQL Database ###
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: innocent
      MYSQL_ROOT_PASSWORD: innocent
      MYSQL_USER: user
      MYSQL_DATABASE: innocent_db
    restart: always
    volumes:
      - mysql_db_data:/var/lib/mysql

### MySQL Adminer ###
  adminer:
    container_name: adminer_container
    image: adminer
    depends_on:
      - mysql
    environment:
        ADMINER_DEFAULT_SERVER: mysql
        ADMINER_DESIGN: galkaev
    ports:
      - "8888:8888"
    restart: always

  ### API Spring Boot ###

  server:
    container_name: appserver
    image: fullstack_build
    depends_on:
      - mysql
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/innocent_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    ports:
          - "8080:8080"
    restart: always